name: Test CI

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # 解決 "fatal: No names found" 報錯

    - name: set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Git describe
      id: ghd
      uses: proudust/gh-describe@v2.1.0
      with:
        exclude: v*-*

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build Debug APK
      # 使用 assembleDebug 跳過 Release 所需的簽名配置
      run: ./gradlew assembleDebug -P versionName=${{ steps.ghd.outputs.describe }}

    - name: Collect artifact name
      run: |
        # 尋找所有生成的 APK 並設定環境變數
        for variant in vc105 normal; do
          apk_path=$(find push/build/outputs/apk/$variant/debug/ -name "*.apk" | head -n 1)
          if [ ! -z "$apk_path" ]; then
            artifact_name=$(basename -s .apk "$apk_path")
            echo "${variant}_debug_artifact=$artifact_name" >> $GITHUB_ENV
          fi
        done

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4.6.0
      with:
        name: debug-apks
        path: push/build/outputs/apk/*/debug/*.apk

    - name: Get Version Name
      id: gvn
      run: |
        # 從檔案名提取版本號，若提取失敗則使用 Git Describe 的結果
        artifact_path=$(find push/build/outputs/apk/ -name "*.apk" | head -n 1)
        version=$(basename "$artifact_path" | sed -r 's/.*(v[0-9]+\.[0-9]+\.[0-9]+).*/\1/' || echo "${{ steps.ghd.outputs.describe }}")
        echo "version=$version" >> $GITHUB_OUTPUT

    - name: Release
      uses: softprops/action-gh-release@v2
      # 僅在手動執行或推送到 Tag 時發布到 Release 頁面
      if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch'
      with:
        name: ${{ steps.gvn.outputs.version }}
        tag_name: ${{ steps.gvn.outputs.version }}
        target_commitish: ${{ steps.ghd.outputs.sha }}
        prerelease: true
        files: push/build/outputs/apk/*/debug/*.apk
